// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOd-o-4X4riJw4o3FrE9ySlsp8MdV6-2U',
    appId: '1:427760106998:android:101ce0560eecab0eac5bd7',
    messagingSenderId: '427760106998',
    projectId: 'people-528cb',
    databaseURL: 'https://people-528cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'people-528cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfDGYBu-TKFPzqJZCQJl1VxKbkLQXSdOg',
    appId: '1:427760106998:ios:d8f7f457e4ac86ccac5bd7',
    messagingSenderId: '427760106998',
    projectId: 'people-528cb',
    databaseURL: 'https://people-528cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'people-528cb.appspot.com',
    androidClientId: '427760106998-k526tojdlm1641do7igg591bob3pp7g2.apps.googleusercontent.com',
    iosClientId: '427760106998-itmkes037v1pau62e0bcro0s9lpbvfsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.people',
  );
}
